// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsAPI.Model;

#nullable disable

namespace StudentsAPI.Migrations
{
    [DbContext(typeof(DgAkademiContext))]
    partial class DgAkademiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentsAPI.Model.Class", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nchar(300)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK_Class");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("StudentsAPI.Model.Students", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("Classid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("classid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Classid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nchar(300)")
                        .HasColumnName("email")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nchar(300)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nchar(300)")
                        .HasColumnName("password")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK_dbo.student");

                    b.ToTable("student", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
